name: Halyard-star CI

on:
  push:
    branches: [ latest ]
  pull_request:
    branches: [ latest ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    - name: Build
      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V --no-transfer-progress

    - name: Tests
      env:
        MAVEN_OPTS: -Xmx256m -XshowSettings:vm
      run: mvn test -B

    - name: Upload code coverage
      uses: codecov/codecov-action@v2

    - name: Release zips
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          sdk/target/halyard-sdk-*.zip
          webapps/target/rdf4j-*.war
