#!/bin/sh
halyard_home="$(dirname "${0}")"
libjars="$(echo "$halyard_home"/lib/*.jar | tr ' ' ',')"
export HADOOP_CLASSPATH=`hadoop classpath`:`hbase classpath`
hadoop jar "$halyard_home/lib/halyard-tools-1.3-SNAPSHOT.jar" com.msd.gin.halyard.tools.HalyardBulkLoad -conf /etc/hbase/conf/hbase-site.xml -conf $halyard_home/halyard-defaults.xml -libjars $libjars "$@"
