#!/bin/sh
halyard_home="$(dirname "${0}")"
libjars="$(echo "$halyard_home"/lib/*.jar | tr ' ' ',')"
export HADOOP_CLASSPATH="$halyard_home/lib/*:`hadoop classpath`:`hbase classpath`"
hadoop com.msd.gin.halyard.tools.HalyardMain "$1" -conf /etc/hbase/conf/hbase-site.xml -conf $halyard_home/halyard-defaults.xml -libjars $libjars "${@:2}"
