#!/bin/sh
lib="$(dirname "${0}")/lib"
libjars="$(echo "$lib"/*.jar | tr ' ' ',')"
export HADOOP_CLASSPATH=`hadoop classpath`:`hbase classpath`:/etc/hive/conf/
hadoop jar lib/halyard-tools-1.0.jar com.msd.gin.halyard.tools.HalyardHiveLoad -conf /etc/hbase/conf/hbase-site.xml -libjars $libjars "$@"
