#!/bin/sh
halyard_home="$(dirname "${0}")"
libjars="$(echo "$halyard_home"/lib/*.jar | tr ' ' ',')"
export HADOOP_CLASSPATH=`hadoop classpath`:`hbase classpath`:"$halyard_home"/lib/*
hadoop com.msd.gin.halyard.tools.HalyardParallelExport -conf /etc/hbase/conf/hbase-site.xml -conf $halyard_home/halyard-defaults.xml -libjars $libjars "$@"
